# 智付通測試平台: https://cwww.spgateway.com/
# 信用卡測試卡號: 4000-2211-2222-2222

default: &default
  merchant_id: MS35549602
  hash_key: vO0CaLGdfRzJUKd8N4gjAuRHKb6LgM5w
  hash_iv: aINGNEwjzxMYJRvC
  url: https://ccore.spgateway.com/MPG/mpg_gateway
  notify_url: http://requestbin.fullcontact.com/tn68wjtn
  #必須要真實網址
  #https://requestbin.fullcontact.com/

development:
  <<: *default

staging:
  <<: *default

test:
  <<: *default

production:
  <<: *default